### ISSUE TITLE
Add function to return post IDs

### ISSUE THREAD

**Issue by anastis** [cabrerahector/wordpress-popular-posts#110]
While the plugin is very powerful and provides a good degree of customizability (and kudos for your work), the existing system of providing custom HTML as a string certainly has its uses, but lacks the ability to integrate cleanly with themes. For one, template parts need to be duplicated/rewritten using the plugin's placeholders, which violates the DRY principle.

In order to give developers further freedom and have the ability to deeply integrate the plugin with themes, a function (or public method) should be available that returns either a WP_Query object, or an array of post IDs (which can easily be used in a new WP_Query object).

Having such a function, allows using standard practices as **The Loop** and `get_template_part()` and can keep a theme clean, following the DRY principle.

This should be a combination of `wpp_get_mostpopular()` + `shortcode()` + `__get_popular_posts()` + `_query_posts()` .

Ideally:
- It should accept an array of arguments, just like `wpp_get_mostpopular()`
- It should provide sanitization and defaults like `shortcode()`, without any of the templating args.
- It should leverage the transients already in place by `__get_popular_posts()`
- It should actually return what `_query_posts()` returns.

You do a great job gathering the data.
Now, provide a theme-developer-friendly way to use them, please! :smile:

**Comment by cabrerahector** [comment]
PRs are welcome if you have specific ideas on how to accomplish what you
have suggested here without having to refactor WPP's code.

P .S.: I assume you have seen/tried WPP's filter hooks already, correct?

**Comment by anastis** [comment]
Indeed I've seen them.
The theme we're building depends on other plugins as well, so there's a lot of logic that can't really be duplicated in a per-post basis with the existing system, plus custom image sizes, additional author meta that needs to be displayed, etc. 

I'm a subversion man myself, and I didn't get a change to learn git+hub yet so you'll need to forgive me as I'll stay away from PRs for now.

I can't really see it happening in its entirety without a considerable amount of refactoring.

However, a subset of the points above can be achieved, I think pretty easily:
- Break __get_popular_posts() in two functions, one that fetches the posts, and one that displays them.
- Make public the one that fetches the posts, and return `$mostpopular`. Since the class is a singleton, developers can create a reference and call that from their code. It uses the transients, so no overhead there.
Existing functionality doesn't get affected, and devs can get whatever they want. You could even leave it undocumented to avoid the burden of support. Those who seek, find. :speak_no_evil: 

I'm not really familiar with your code, so most probably I'm missing something, I do however think it's a must-have and I'm willing to help however I can.

**Comment by rahulnever2far** [comment]
+1

This would be insanely helpful!

**Comment by cabrerahector** [comment]
Hey guys!

It's been quite a while, so how about some updates?

As expressed above, adding some sort of API to allow other developers get raw data would require refactoring WPP's code. Initially I wasn't very fond of the idea since code refactoring is usually quite a bit of work ... but I ended up doing it anyways: I'm refactoring WPP's code following the [SOLID principles](https://scotch.io/bar-talk/s-o-l-i-d-the-first-five-principles-of-object-oriented-design "S.O.L.I.D: The First 5 Principles of Object Oriented Design").

So far:

- I've managed to build a core class that queries the database and returns an array of posts objects. The class can be passed an array of parameters - _nearly_ identical to how the [wpp_get_mostpopular() template tag](https://github.com/cabrerahector/wordpress-popular-posts/wiki/2.-Template-tags#wpp_get_mostpopular) works. Once WordPress loads WPP, this class will be available and you will be able to use it. Right now it's completely functional.
- The code is being divided into single responsibility classes which will make maintaining / extending WPP much, much easier.

What's next:

- A final 3.3.x release (includes a couple of minor fixes and improvements) will be pushed to WordPress' repo. This will be the last non-SOLID version of WPP.
- I still need to integrate the class (currently named as WPP_Query, might change it) with the widget. This is what I'll be doing in the upcoming days.
- The admin section needs some rework as well. A new Stats section has been under testing for a few months now and I believe it's ready for the masses - I'm sure you will like it.

That's it for now!

**Comment by anastis** [comment]
That's great news! 👯

**Comment by rahulnever2far** [comment]
@cabrerahector Thank you so much for the time and effort you are putting into this plugin. I'm sure a lot of developers who are integrating this plugin into their would appreciate it :+1: 

Could you share a rough estimate of time for the release that would include the ability to get just the data? I'm planning to deeply integrate your plugin in my next theme. 

PS: How about creating a new branch called dev, beta or something more appropriate, where others could test new features before public release? That could help you get rid of bugs (if any) in early stages.

**Comment by cabrerahector** [comment]
> Could you share a rough estimate of time for the release that would include the ability to get just the data?

Ideally, some time later this month. Mid/late July, most likely. I still have a couple of freelance projects going on and I would also like to spend some time testing the SOLID version of WPP before releasing it to the public. I'll keep you guys posted, I'm probably going to need your help with testing.

> How about creating a new branch called dev, beta or something more appropriate, where others could test new features before public release?

I've been meaning to do that for some time now. However, I still don't fully understand how to properly work with GIT branches yet. Now might be the perfect opportunity to give them another try. Thanks for the suggestion :)

**Comment by rahulnever2far** [comment]
> Ideally, some time later this month. Mid/late July, most likely.

That would be great! :+1: 

> I've been meaning to do that for some time now. However, I still don't fully understand how to properly work with GIT branches yet.

Branches in Git could be a bit intimidating at first, especially if you are learning all by yourself. But once understand how it works, its pretty awesome.

I'm not sure how much you know about branching Git. Articles like these helped me understand the concept when I was learning Git :)
http://rypress.com/tutorials/git/branches-1
http://rypress.com/tutorials/git/branches-2

**Comment by cabrerahector** [comment]
Thanks for the links, @rahulnever2far! Just took a quick peek at the first one and the article seems quite easy to follow. I'll make sure to read them as soon as possible :)

**Comment by cabrerahector** [comment]
Hey guys, it's been a while!

Just pushed WPP v.3.3.4 into the wild. It should be live on the WordPress' repo in a few minutes.

About the SOLIDish version of WPP, it's coming along quite nicely! Most of the code refactoring is already done and a few core functions are already in place:

- Plugin is already tracking the views.
- Widget is available and working and so is the [wpp] shortcode.
- Admin section is working as well (there's still one new feature that needs to be added but that'll happen once I'm done with the rest of the core features.)

TODO:

- Plugin activation / deactivation processes & checks (DB tables installation / upgrades, Multisite check, textdomain load, etc.)
- Views Log trimming.
- Uninstall process.
- Template tags: wpp_get_mostpopular() (which I might be renaming to wpp_get_popular(), btw), wpp_get_views().
- Multilingual support (WPML, qTranslateX, etc.)

Once all these are done, I'll attempt to create a _4.0_ branch so you guys can help me test it before releasing it to the official repo - that's if you don't mind of course.

**Comment by rahulnever2far** [comment]
@cabrerahector how is version 4.0 coming along? Any idea when it's gonna be ready?

**Comment by cabrerahector** [comment]
Hey @rahulnever2far!

Wow, 15 days since your comment went by without notice! I've been horribly busy in the past month and so there hadn't been much progress with 4.0... _until now_.

I spent a few hours today migrating the remaining features from the latest official version to 4.0. Except for multilingual support & the ability to pick a different thumbnail source (4.0 includes a new WPP_Image class which handles the whole thumbnail creation / rendering process, and right now it only builds / retrieves thumbnails from the featured image), I'd say that 4.0 is ready for production as it is now.

I'll push the new _wpp4_ branch in a few hours so you guys can play around with it.

**P.S.:** The Git tutorials were a great help! Thanks again!!

**Comment by cabrerahector** [comment]
Alright guys, the _wpp4_ branch is out!

Version 4.0.0 includes a lot of changes. One of them is the inclusion of a new class called WPP_Query (which I mentioned before) that basically retrieves the popular posts from the database. This class returns an array of objects whose fields varies according to the parameters passed to WPP_Query, with the exception of _id_, _title_ and _uid_ (author ID) which are always present.

```php
<?php
$args = array(
    'range' => 'last7days',
    'limit' => 8,
    'post_type' => 'post'
);
$popular = new WPP_query( $args );

var_dump( $popular->get_posts() ); // Outputs array of objects if results were found, or an empty array if not
?>
```

As I mentioned before, the arguments are _nearly_ identical to those used with the wpp_get_mostpopular() template tag. For a complete list of parameters, check the widget_options array in the helper class (includes/class-wordpress-popular-posts-helper.php).

Keep in mind that this is still a WIP so things might change without prior notice.

If you spot a bug or feel that something can be improved please feel free to share your thoughts here :)

**Comment by rahulnever2far** [comment]
I'll try wpp4 today and let you know how it goes 👍

**Comment by rahulnever2far** [comment]
I activated the v4 of the plugin and tried the code you provided, it returns an empty array.

**Comment by cabrerahector** [comment]
Yep, that's to be expected - if no posts match the criteria set via parameters, the WPP_Query class will return an empty array (a "Sorry, no data so far" message, PHP style). Otherwise you should get an array similar to this one:

```php
array(1) {
  [0]=>
  object(stdClass)#278 (4) {
    ["id"]=>
    string(1) "1"
    ["title"]=>
    string(12) "Hello world!"
    ["uid"]=>
    string(1) "1"
    ["pageviews"]=>
    string(1) "1"
  }
}
```

**Comment by rahulnever2far** [comment]
Og okay. I'll try again then 👍

**Comment by ehabrahim** [comment]
@cabrerahector How to get array of _**just post ids**_ ?

**Comment by cabrerahector** [comment]
Hey @ehabrahim,

I already answered your question [here](https://wordpress.org/support/topic/get-posts-ids-show-the-most-popular-posts-within-24-hours-range/#post-11287439).
