### ISSUE TITLE
Add WP REST API support

### ISSUE THREAD

**Issue by ChazUK** [cabrerahector/wordpress-popular-posts#116]
Is there any roadmap to add WP REST API support for this plugin?

**Comment by cabrerahector** [comment]
Hi Charlie!

Currently there are no plans to integrate the plugin with the WP REST API,
although it's not something out of the question.

How would you (or any other user out there) benefit from having WPP
supporting this API? If you have an use case, please share it.

**Comment by ChazUK** [comment]
I believe a lot of people are starting to use Wordpress as a standalone Content Management System, and building separate sites in frameworks like React/Angular using the WP REST API.

**Comment by alonbilu** [comment]
I've noticed that recently, many bloggers are moving to mobile apps, which allows their users a faster access to the blog's content. Many of them use the REST API for this purpose...

Supporting the restful api, will save a lot of time, if I wish to allow my users to to view the popular posts of my blog (and not just the recent posts).

**Comment by cabrerahector** [comment]
Hi there!

This is a valid use case, so thanks for sharing the thought.

As I mentioned before, I'm not familiar with the REST API yet. What kind of
response should WPP return via this API? An array of post objects? An XML?
JSON? A HTML list?

**Comment by alonbilu** [comment]
And array of post objects in JSON format -
------------------------
For example, with the URL http://example.com/wp-json/wp/v2/posts/123:

The “route” is wp/v2/posts/123 - The route doesn’t include wp-json because wp-json is the base path for the API itself.

This route has 3 endpoints:

GET triggers a get_item method, returning the post data to the client.
PUT triggers an update_item method, taking the data to update, and returning the updated post data.
DELETE triggers a delete_item method, returning the now-deleted post data to the client.
------------------------

Here's a sample output -

{"id":70199,"date":"2016-09-15T15:17:57","date_gmt":"2016-09-15T12:17:57","guid":{"rendered":"http:\/\/www.example.com\/?p=70199"},"modified":"2016-09-15T15:17:57","modified_gmt":"2016-09-15T12:17:57","slug":"post-slug","type":"post","link":"http:\/\/www.example.com\/post-slug\/","title":{"rendered":"post title"},"content":{"rendered":"<input type=\"hidden\" value=\"\" data-frizzlyPostContainer=\"\" data-frizzlyPostUh\/p>\n<h2>1.<\/h2>\n<div id=\"attachment_70200\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70200\" src=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/1-27.jpg?resize=650%2C636\" alt=\"Credit:\" srcset=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/1-27.jpg?w=650 650w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/1-27.jpg?resize=300%2C294 300w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/1-27.jpg?resize=60%2C59 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/er967.tumblr.com\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 tumblr.com  <\/a><\/p><\/div>\n<h2>2.<\/h2>\n<div id=\"attachment_70201\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70201\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/2-26.jpg?resize=650%2C506\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/2-26.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/2-26.jpg?resize=300%2C234 300w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/2-26.jpg?resize=60%2C47 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/www.paulagoble.com\/#\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 Paula Goble  <\/a><\/p><\/div>\n<h2>3.<\/h2>\n<div id=\"attachment_70202\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70202\" src=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/3-26.jpg?resize=650%2C765\" alt=\"Credit:\" srcset=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/3-26.jpg?w=650 650w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/3-26.jpg?resize=255%2C300 255w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/3-26.jpg?resize=60%2C71 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/scontent.xx.fbcdn.net\/hphotos-xfp1\/v\/t1.0-9\/10451008_675101815978410_3810557563658212917_n.jpg?oh=c2066a61d7c41477d62c087a095b852c&#038;oe=55862E1D\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 facebook.com  <\/a><\/p><\/div>\n<h2>4.<\/h2>\n<div id=\"attachment_70203\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70203\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/4-26.jpg?resize=650%2C979\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/4-26.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/4-26.jpg?resize=199%2C300 199w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/4-26.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/pin\/353040058264042828\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<h2>5.<\/h2>\n<div id=\"attachment_70204\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70204\" src=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/5-24.jpg?resize=650%2C866\" alt=\"Credit:\" srcset=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/5-24.jpg?w=650 650w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/5-24.jpg?resize=225%2C300 225w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/5-24.jpg?resize=60%2C80 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/tigerdragoon\/mommy-and-daughter-matching\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<h2>6.<\/h2>\n<div id=\"attachment_70205\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70205\" src=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/6-23.jpg?resize=650%2C975\" alt=\"Credit:\" srcset=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/6-23.jpg?w=650 650w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/6-23.jpg?resize=200%2C300 200w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/6-23.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/www.melissadawnphotoblog.com\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 Melissa Dawn  <\/a><\/p><\/div>\n<h2>7.<\/h2>\n<div id=\"attachment_70206\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70206\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/7-19.jpg?resize=650%2C975\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/7-19.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/7-19.jpg?resize=200%2C300 200w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/7-19.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/www.spivakea.ru\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 \u0415\u043b\u0435\u043d\u0430 \u0421\u043f\u0438\u0432\u0430\u043a  <\/a><\/p><\/div>\n<h2>8.<\/h2>\n<div id=\"attachment_70207\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70207\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/8-17.jpg?resize=650%2C690\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/8-17.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/8-17.jpg?resize=283%2C300 283w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/8-17.jpg?resize=60%2C64 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.facebook.com\/SaidMhamadPhotography\/photos\/a.336037933133346.73888.335960369807769\/869398246463976\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 Said Mhamad  <\/a><\/p><\/div>\n<h2>9.<\/h2>\n<div id=\"attachment_70208\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70208\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/9-15.jpg?resize=650%2C650\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/9-15.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/9-15.jpg?resize=150%2C150 150w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/9-15.jpg?resize=300%2C300 300w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/9-15.jpg?resize=60%2C60 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.facebook.com\/ArchiDesiign\/photos\/pcb.675103562644902\/675101869311738\/?type=1&#038;theater\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 facebook.com  <\/a><\/p><\/div>\n<h2>10.<\/h2>\n<div id=\"attachment_70209\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70209\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/10-13.jpg?resize=650%2C647\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/10-13.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/10-13.jpg?resize=150%2C150 150w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/10-13.jpg?resize=300%2C300 300w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/10-13.jpg?resize=60%2C60 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.facebook.com\/ArchiDesiign\/photos\/pcb.675103562644902\/675101932645065\/?type=1&#038;theater\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 facebook.com  <\/a><\/p><\/div>\n<p><\/p>\n<h2>11.<\/h2>\n<div id=\"attachment_70210\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70210\" src=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/11-12.jpg?resize=650%2C973\" alt=\"Credit:\" srcset=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/11-12.jpg?w=650 650w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/11-12.jpg?resize=200%2C300 200w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/11-12.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/www.flickr.com\/photos\/a-peril\/3879201716\/in\/pool-27916970@N00\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 April Bauknight  <\/a><\/p><\/div>\n<h2>12.<\/h2>\n<div id=\"attachment_70211\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70211\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/12-11.jpg?resize=650%2C980\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/12-11.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/12-11.jpg?resize=199%2C300 199w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/12-11.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.facebook.com\/ArchiDesiign\/photos\/pcb.675103562644902\/675102322645026\/?type=1&#038;theater\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 facebook.com  <\/a><\/p><\/div>\n<h2>13.<\/h2>\n<div id=\"attachment_70212\" class=\"wp-caption alignnone\" style=\"width: 650px\"><img class=\"size-full wp-image-70212\" src=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/13-10.jpg?resize=640%2C534\" alt=\"Credit:\" srcset=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/13-10.jpg?w=640 640w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/13-10.jpg?resize=300%2C250 300w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/13-10.jpg?resize=60%2C50 60w\" sizes=\"(max-width: 640px) 100vw, 640px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/pin\/256705247486340644\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<h2>14.<\/h2>\n<div id=\"attachment_70213\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70213\" src=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/14-11.jpg?resize=650%2C975\" alt=\"Credit:\" srcset=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/14-11.jpg?w=650 650w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/14-11.jpg?resize=200%2C300 200w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/14-11.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/pin\/256705247486251299\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<h2>15.<\/h2>\n<div id=\"attachment_70214\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70214\" src=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/15-10.jpg?resize=650%2C1012\" alt=\"Credit:\" srcset=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/15-10.jpg?w=650 650w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/15-10.jpg?resize=193%2C300 193w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/15-10.jpg?resize=60%2C93 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/www.flickr.com\/photos\/19carla98\/3752488066\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 carla dance  <\/a><\/p><\/div>\n<h2>16.<\/h2>\n<div id=\"attachment_70215\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70215\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/16-7.jpg?resize=650%2C930\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/16-7.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/16-7.jpg?resize=210%2C300 210w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/16-7.jpg?resize=60%2C86 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/pin\/256705247486206528\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<h2>17.<\/h2>\n<div id=\"attachment_70216\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70216\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/17-8.jpg?resize=650%2C432\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/17-8.jpg?w=650 650w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/17-8.jpg?resize=300%2C199 300w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/17-8.jpg?resize=60%2C40 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/cherry-girl010.tumblr.com\/post\/53192817440\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 tumblr.com  <\/a><\/p><\/div>\n<h2>18.<\/h2>\n<div id=\"attachment_70217\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70217\" src=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/18-8.jpg?resize=650%2C969\" alt=\"Credit:\" srcset=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/18-8.jpg?w=650 650w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/18-8.jpg?resize=201%2C300 201w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/18-8.jpg?resize=60%2C89 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/500px.com\/photo\/1985941\/dreams-by-natalia-melnikova\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 Natalia Melnikova  <\/a><\/p><\/div>\n<h2>19.<\/h2>\n<div id=\"attachment_70218\" class=\"wp-caption alignnone\" style=\"width: 660px\"><img class=\"size-full wp-image-70218\" src=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/19-8.jpg?resize=650%2C975\" alt=\"Credit:\" srcset=\"http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/19-8.jpg?w=650 650w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/19-8.jpg?resize=200%2C300 200w, http:\/\/i0.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/19-8.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 650px) 100vw, 650px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/pin\/256705247486185081\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<h2>20.<\/h2>\n<div id=\"attachment_70219\" class=\"wp-caption alignnone\" style=\"width: 650px\"><img class=\"size-full wp-image-70219\" src=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/20-7.jpg?resize=640%2C960\" alt=\"Credit:\" srcset=\"http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/20-7.jpg?w=640 640w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/20-7.jpg?resize=200%2C300 200w, http:\/\/i1.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/20-7.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 640px) 100vw, 640px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"http:\/\/benchristensenphoto.com\/weddings\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 Ben Christensen  <\/a><\/p><\/div>\n<h2>21.<\/h2>\n<div id=\"attachment_70220\" class=\"wp-caption alignnone\" style=\"width: 650px\"><img class=\"size-full wp-image-70220\" src=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/21-6.jpg?resize=640%2C960\" alt=\"Credit:\" srcset=\"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/21-6.jpg?w=640 640w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/21-6.jpg?resize=200%2C300 200w, http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/21-6.jpg?resize=60%2C90 60w\" sizes=\"(max-width: 640px) 100vw, 640px\" data-recalc-dims=\"1\" \/><p class=\"wp-caption-text\" dir=\"rtl\">Credit: <a href=\"https:\/\/www.pinterest.com\/pin\/256705247486056646\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">\u00a9 pinterest.com  <\/a><\/p><\/div>\n<p>\u05de\u05e7\u05d5\u05e8: <a href=\"https:\/\/brightside.me\/article\/like-mother-like-daughter-20-photos-where-moms-and-daughters-look-alike-70305\/\" data-wpel-link=\"external\" target=\"_blank\" rel=\"external noopener noreferrer\">brightside<\/a><\/p>\n"},"excerpt":{"rendered":"<input type=\"hidden\" value=\"\" data-frizzlyPostContainer=\"\" data-frizzlyPostUrl=\"http:\/\/www.example.com\/post-slug\/\" data-frizzlyPostTitle=\"post title\" data-frizzlyHoverContainer=\"\"><p>:)<\/p>\n"},"author":17,"featured_media":70231,"comment_status":"closed","ping_status":"closed","sticky":false,"format":"standard","categories":[15,6],"tags":[],"featured_image_thumbnail":"http:\/\/i2.wp.com\/www.example.com\/wp-content\/uploads\/2\/2016\/09\/14-09-2016-23-29-36.png?fit=800%2C420","_links":{"self":[{"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/posts\/70199"}],"collection":[{"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/users\/17"}],"replies":[{"embeddable":true,"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/comments?post=70199"}],"version-history":[{"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/posts\/70199\/revisions"}],"wp:featuredmedia":[{"embeddable":true,"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/media\/70231"}],"wp:attachment":[{"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/media?parent=70199"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/categories?post=70199"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/www.example.com\/wp-json\/wp\/v2\/tags?post=70199"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}

**Comment by ChazUK** [comment]
Well that email escalated, can you switch that to a code block using \`\`\` to start and \`\`\` to end

**Comment by cabrerahector** [comment]
Yeah, I was a bit surprised when I read that e-mail on my Nexus. It's a bit late now since everyone subscribed to this topic got that message that way already, but I edited @alonbilu's comment anyways.

@alonbilu thanks for the input. I'll look into the REST API as soon as I'm done with [this](https://github.com/cabrerahector/wordpress-popular-posts/issues/110#issuecomment-244611584).
