### ISSUE TITLE
hello can make popular post like this with wordpress popular posts

### ISSUE THREAD

**Issue by asagishi** [cabrerahector/wordpress-popular-posts#120]
hello sir can make popular post like this ? http://prntscr.com/dfpigz  
i create php script but i am newbie .. 
```php
<div class="preks"><h3><b>Popular Series</b></div>
<?php
$popularpost = new WP_Query( array( 'post_type' => anime, 'posts_per_page' => 5, 'meta_key' => 'wpb_post_views_count', 'orderby' => 'meta_value_num' ) );
while ( $popularpost->have_posts() ) : $popularpost->the_post(); ?>
<div class='polarpost'>
<div class='polargambar'><?php if ( has_post_thumbnail() ) { the_post_thumbnail(); }?></div>
<div class='polarjdl'><a href="<?php the_permalink() ?>" title="<?php the_title(); ?>"><h2><?php the_title(); ?></h2></a></div>
<div class='polargenre'><?php echo get_the_term_list( $post->ID, 'genre', '<p><b>Genre:</b> ', ', ', '</p>' ); ?></div>
</div>
<?php endwhile; ?>
```

itry make popular post with that script but i got problem with share link on my webiste ,, everytime i share my link on facebook the tumbnail appear is the tumbnail from widget not from my pos..... can make popular post like my screenshoot on wordpress popular posts sir?

**Comment by cabrerahector** [comment]
Hi there!

> everytime i share my link on facebook the tumbnail appear is the tumbnail from widget not from my pos.....

That's theme related.

When you share an URL on Facebook, Facebook's Crawler checks loads it and if the web page has the [Open Graph metatags](https://developers.facebook.com/docs/sharing/webmasters) properly configured it'll load the right image, otherwise I believe it'll use the first image it finds in the page instead.

> can make popular post like my screenshoot on wordpress popular posts sir?

Yes, WPP can be themed so it looks like the one on your screenshot. If you share your site's URL I might help you out with that once my current work load eases up a bit.
