### ISSUE TITLE
Show posts in the subcategory as well

### ISSUE THREAD

**Issue by hardfire** [cabrerahector/wordpress-popular-posts#123]
First of all, amazing plugin. I have been playing around and realized that when i want to show all the popular posts for a category, the posts for its subcategories is not listed. Is there a way to get this done automatically? My another option would be to wrap the shortcode in another shortcode and then query the categories subcategories and pass it to the plugin. But maybe an elegant solution is there in the plugin.

**Comment by cabrerahector** [comment]
Hi there!

The reason why the plugin doesn't retrieve posts from child category(ies) from a given category(ies) is that listing posts from a category not specifically requested by the user (that's you!) might not be the desired/expected behavior in most cases (not yours, obviously hehe) so I decided to keep it simple and have WPP get the posts only from the specified category ID(s).

I could offer some ideas if you're willing to share some more details on what you're trying to achieve with the plugin.

**Comment by hardfire** [comment]
Aha! I understand.

My exact use case is that I have my posts in a category hierarchy and in the front page, i would like to show top 3 posts for each category (including sub-category) with other content. 

I am using the WPP shortcode as of now. Its probably the most common use-case for WPP.

Though just thinking, what are the implications of putting a post in both the parent category and the sub-category (apart from the URL structure). I'll read through the docs to see if any, if not then i can just add the post to both categories and that solves my problem, in a rather elegant way.
