### ISSUE TITLE
Still have an issue with the plugin

### ISSUE THREAD

**Issue by rockysbuddy** [cabrerahector/wordpress-popular-posts#144]
The popular posts (or top 5 as Ive named it on my site page) plugin is causing the full blogs to show at the bottom of the page. I know it is the plugin because when I take away the Top 5 ( where I used your WPP plugin) on the page. The 5 full blogs listed go away on the bottom of the page. See http://liznierzwicki.com/heaven/   for reference.. Thank you, Christi Mcilwain ceo | creative director

**Comment by cabrerahector** [comment]
Hi Christi,

I asked you [here](https://github.com/cabrerahector/wordpress-popular-posts/issues/143) to provide screenshots and didn't hear from you for over a week (11 days, to be exact) hence I closed the other issue figuring you had already sorted it out. Since that's not the case:

- Please share the screenshots as I previously requested.
- From the source code of your site I found that you (or your developer) have customized the HTML output from WPP a bit. Could you please tell me exactly how you (or your developer) did this customization?

**P.S.:** I edited your post, writing in all caps is considered rude.

**Comment by rockysbuddy** [comment]
There is no need to see screen shots, all you need to do is go to the link to view what I am talking about. Again here is the link: http://liznierzwicki.com/heaven/  

No code was manipulated whatsoever. I am the developer. 

Thank you, Christi Mcilwain ceo | creative director

**Comment by cabrerahector** [comment]
I'm sorry, but [this](https://prnt.sc/fog9en) is not the "stock" HTML markup from the plugin ([here's what WPP outputs if you use the default HTML markup](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L1951-L1968).) You must have changed something, hence my question above.

Unless you can provide further details about how you're using the plugin on your site there's little I can do. Help me help you.

**Comment by rockysbuddy** [comment]
Ok, I deleted your plugin (WPP) then installed it. With NO manipulation of the code whatsoever. It is still listing the 5 popular posts (post names) at the top like I wanted it but then shows those same 5 popluar FULL blogs at the bottom of the page. There is no code at the bottom that tells the page to show them. http://liznierzwicki.com/heaven/

**To clarify what I have done exactly:** I downloaded the plugin, activated it. Placed the WPP into the sidebar blog section in widgets. Then named the title Top 5: Then set it to show 5 posts. That is all I did with the plugin. I have no idea what you are talking about "not the "stock" HTML markup from the plugin (here's what WPP outputs if you use the default HTML markup.) You must have changed something, hence my question above." means.

**Comment by cabrerahector** [comment]
Alright, we're getting some progress. Thank you, that's exactly what I was asking from you.

Just checked your site again and the source code of the widget is still the same as before (and you can tell because it even looks the same way as it did before you deleted it.) If it's not you who's changing the HTML output of the WPP widget then something else is. Maybe your theme, or maybe some other plugin (but I bet is the former), but definitely something is making changes to WPP (and it might be also the same reason why your site breaks like that.)

Did you build this theme?

**Comment by rockysbuddy** [comment]
No one is touching this site but me. I did not create the theme. I purchased the theme. Then added your plugin, which apparently doesn't work with my site theme.

**Comment by cabrerahector** [comment]
It might be something else entirely, I'm just speculating here. Are you developing this site locally? If so, then please try the following:

1. Switch for a moment to another theme, like Twenty Seventeen for example.
2. Add the WPP widget to the sidebar, keeping its default configuration as is.
3. Check the site.

Please report back what the results are.

**Comment by rockysbuddy** [comment]
Nevermind. I am deleting your plugin and using another one.  I don't have time to mess with this any longer.

**Comment by cabrerahector** [comment]
Alright, no problem.
