### ISSUE TITLE
Thumbnail - first image, there is a problem with an address (src)

### ISSUE THREAD

**Issue by tonyAndr** [cabrerahector/wordpress-popular-posts#145]
When I'm trying to get fisrt image as a thumbnail in the side widget, I get placeholder instead. 

The reason is that my html code looks like this: 
`<img src="/wp-content/uploads/YY/MM/img.jpg" /> 
`
I don't use full address of an img. 

Some posts have full src with domain like 

`<img src="http://site.com/wp-content/uploads/YY/MM/img.jpg" /> 
`
 and thumbnails work fine with them. 

How can I fix this issue? Most of my posts don't have full address and I'm not gonna change them all manualy.

**Comment by cabrerahector** [comment]
Hi there!

When retrieving the thumbnails WPP expects the full URL -as you already noticed- because this is the standard behavior in WordPress. Yours is an edge-case so it's not really an issue caused by WPP.

With that being said, here are a couple of ideas to work around the issue:

- Unless you have a valid reason to have your images use relative URLs instead of absolute ones, you could just convert all relative URLs to absolute URLs by running the following query in phpmyadmin (and this way avoiding having to change every one one of them manually):
`UPDATE wp_posts SET post_content = replace(post_content, '<img src="/wp-content/uploads/', '<img src="http://www.your-domain.com/wp-content/uploads/');`
Change `http://www.your-domain.com` to your actual domain (and **get a backup of your DB** before trying this just in case something goes wrong / you change your mind.)
- Have WPP load thumbnails from a [different source](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-does-wordpress-popular-posts-pick-my-posts-thumbnails) (although this probably means manual work anyways.)

**Comment by tonyAndr** [comment]
Yeah... Anyways nice plugin, so probably I'll convert them. Thanks for the query.
