### ISSUE TITLE
Empty strings in the args are treated as not existing

### ISSUE THREAD

**Issue by MastaBaba** [cabrerahector/wordpress-popular-posts#149]
If I have this:
```
$args = array(
	'wpp_start' => '',
	'wpp_end' => '',
);
```
I really need to specify this:
```
$args = array(
	'wpp_start' => ' ',
	'wpp_end' => ' ',
);
```

That is, I have to set these arguments to a space. If I set them to empty, the plugin treats them as not set, and returns the default value.

The above is a workaround for unexpected behaviour.

**Comment by cabrerahector** [comment]
Hi there!

That's by design. The default structure of the popular posts list is an unordered list where all posts are wrapped in an UL tag.

Following this idea, the plugin always expects to have posts wrapped in another HTML tag (which is why wpp_start and wpp_end exist.) If they're not set (as you already noticed) they'll fallback to default.
