### ISSUE TITLE
Is it possible to show posts from a set time period?

### ISSUE THREAD

**Issue by Taiiwo** [cabrerahector/wordpress-popular-posts#152]
I realise it's possible to show posts X number of hours/days/minutes from the current time, but is it possible to offset that time, for example, to show the posts with the highest views from yesterday? I'm making a user submitted content site where the most popular user submitted content for any given day is featured on the homepage for the following day.

I would like to be able to do this using a widget or shortcode, but if it's only possible using PHP (Which I suspect to be the case), what is the best practice for adding custom PHP into pages, posts, etc.? I would not mind adding this functionality to the plugin and submitting it as a pull request, just tell me how you want it adding.

**Comment by cabrerahector** [comment]
Hi there!

Possible? Completely. Possible from the plugin? Unfortunately no.

**Comment by Taiiwo** [comment]
Would you like it implemented? I was planning on adding a new argument to "range". I was thinking of calling it "Only yesterday". Would you merge that?

**Comment by cabrerahector** [comment]
Please check my previous comment again.

And no, I believe that while this feature would be nice (and surely a lot people would love to have it), my main concern here is -as I previously expressed- performance.

If I find a better way to do this while maintaining a proper balance with performance, I'll consider implementing it.

**Comment by Taiiwo** [comment]
I was just going to add a date range to the SQL query. Assuming your view records have date formatted representations of when the view was made?

I do plan on having a lot of posts and a _lot_ of visitors (who doesn't?)

**Comment by cabrerahector** [comment]
> I believe that while this feature would be nice (and surely a lot people would love to have it)

I will correct myself here: just remembered that actually some time ago WPP did have a "Yesterday" time range - but apparently not many people were using it back then. I know this because I removed this time range silently and no one seemed to care about it that much (and hence it didn't make it back on the next release :P)

So, feel free to send a PR implementing this. I won't merge it right away, though. If it gets traction / more people request it, I'll consider merging it. Sounds good?
