### ISSUE TITLE
Function request: Exclude the current post

### ISSUE THREAD

**Issue by cawa-93** [cabrerahector/wordpress-popular-posts#160]
I have a suggestion: add the checkbox option to exclude the current post from the sample.
This can be achieved using PHP, but I would like to get this opportunity for the widget.
```php
if (is_single()) {
    $args['pid'] = get_the_id()
}
```
Some like this
![default](https://user-images.githubusercontent.com/1662812/32168672-3c4f9382-bd76-11e7-94a4-725f5426ca5e.png)

**Comment by cabrerahector** [comment]
Hi there,

I realize I took an incredible amount of time to reply to this issue so please accept my apologies.

With that being said, this works:

```php
/**
 * Removes current post/page from the popular list.
 *
 * @param   string      $post_html      The original popular post HTML output
 * @param   object      $popular_post   The popular post object
 * @param   array       $instance       An array containing the options from the widget/shortcode
 *
 * @return  string
 */
function exclude_current_post_from_wpp_list( $post_html, $popular_post, $instance ){

    if ( is_single() && get_queried_object_id() == $popular_post->id )
        return '';

    return $post_html;

}
add_filter( 'wpp_post', 'exclude_current_post_from_wpp_list', 10, 3 );
```

There is a limitation though: if you enable the **Ajaxify widget** feature (Settings > WordPress Popular Posts > Tools), when the plugin requests the popular posts list via [AJAX](https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started#What's_AJAX "What's AJAX?") `is_single()` and `get_queried_object_id()` will return `false` / `null` (because when the checks are run we're no longer on the post/page) and so the current post / page will not be excluded from the listing.

If I can find a solution that:

- works reliably,
- doesn't have any negative impact on current codebase

then I'll reopen this issue and/or leave a comment for discussion.
