### ISSUE TITLE
cat and pid should accept array type when using template tag

### ISSUE THREAD

**Issue by garrettpatterson** [cabrerahector/wordpress-popular-posts#169]
When in the post loop or other areas embedding via the template tag, most Wordpress functions return arrays or integer values.  Ability to optionally pass an array or integer type would simplify the usage:
```php
$args = array(
    'wpp_start'=>'<div class="row">',
    'wpp_end'=>'</div>',
    'cat'=> join(',',wp_get_post_categories(get_the_ID())),
    'pid'=> strval(get_the_ID()),
```

**Comment by cabrerahector** [comment]
Hi there!

Sorry for the late reply.

That should be fairly simple to do. I'll look into it and if implemented I'll post an update here (and probably reference it from the commit if it happens).

**Comment by cabrerahector** [comment]
Took a bit of time but here it is!

A note on usage, though: the `wpp_get_mostpopular()` function still expects an array of integers. Following OP's example, this will work:

```php
$args = array(
    'range' => 'last30days',
    'cat' => wp_list_pluck( get_the_category( get_the_ID() ), 'term_id' ),
);
wpp_get_mostpopular( $args );
```

This will **not** work:

```php
$args = array(
    'range' => 'last30days',
    'cat' => get_the_category( get_the_ID() ),
);
wpp_get_mostpopular( $args );
```

Notice that there are two slight differences:

- We're using [wp_list_pluck()](https://codex.wordpress.org/Function_Reference/wp_list_pluck) to obtain an array of IDs from [get_the_category()](https://developer.wordpress.org/reference/functions/get_the_category/).
- In the example, we're using [get_the_category()](https://developer.wordpress.org/reference/functions/get_the_category/) instead of [wp_get_post_categories](https://developer.wordpress.org/reference/functions/wp_get_post_categories/) for [performance reasons](https://developer.wordpress.org/reference/functions/wp_get_post_categories/#more-information).
