### ISSUE TITLE
No Thumbnail with Template Tags

### ISSUE THREAD

**Issue by moseke** [cabrerahector/wordpress-popular-posts#175]
What is the argument to pass to the wpp_get_mostpopular() function to display thumbnail images?

Here is my current argument:
```
$args = array(
	'limit' 	=> 5,
	'range'		=> 'last7days',
	'order_by'	=> 'views',
	'stats_views'	=> 1, // Show number of views - 1 (true), (0) false
);

wpp_get_mostpopular( $args );
```

I've tested the widget form of this plugin and thumbnails display no problem so it does not appear to be an issue with PHP extensions.

**Comment by moseke** [comment]
Nevermind. So sorry, I kept asking Chrome to search the parameters page for this info and it returned no result. 

My apologies!

**Comment by cabrerahector** [comment]
To not let this question go unanswered since others might stumble into this issue someday, you also need to specify the width & height of the thumbnail for the function to create / retrieve the thumbnail:

```php
<?php
if ( function_exists("wpp_get_mostpopular") ){

    $args = array(
        'limit' => 5,
        'range' => 'last7days',
        'thumbnail_width' => 100,
        'thumbnail_height' => 65
    );
    wpp_get_mostpopular( $args );

}
?>
```

This is kind of a recurrent question though, I might as well change the current behavior and have it display a thumbnail with preset dimensions if not specified by the user.

**Comment by dustinpitcher** [comment]
It seems as though the widget is the only place we're able to actually use the post thumbnails that Wordpress is generating for each post. I have been unable to identify any way of retrieving the existing post thumbnail (NOT the one generated by wpp) when using the template tag or shortcode. Can you confirm or advise how to fetch the thumbnail that already exists (not generating a new one)?

**Comment by cabrerahector** [comment]
> It seems as though the widget is the only place we're able to actually use the post thumbnails that Wordpress is generating for each post.

Indeed, that is the case @dustinpitcher.

At the moment the only way to retrieve the featured image without modifying plugin's code is via [WPP's filter hooks](https://github.com/cabrerahector/wordpress-popular-posts/wiki/3.-Filters) - ergo, by customizing the HTML output via PHP instead of the built-in HTML related parameters.

It is possible to have the `[wpp]` shortcode & the `wpp_get_mostpopular()` template tag retrieve the featured image just like the widget does. All it requires is a couple of additional parameters, missing from the code that registers the shortcode. I might add those in a future release but for the time being you'll have to make do with the above solution.

**P.S.:** out of curiosity, why did you leave this comment on a closed issue that's not even related to the problem you described?

**Comment by cabrerahector** [comment]
Don't worry about it, Dustin. I wasn't attacking you or anything like that. I was genuinely curious, I thought I may have missed something so I asked :)
