### ISSUE TITLE
Is there a way to count views without rest_url?

### ISSUE THREAD

**Issue by portablesoft** [cabrerahector/wordpress-popular-posts#212]
I have disabled the JSON REST API using the following filters:

add_filter('json_enabled', '__return_false');
add_filter('json_jsonp_enabled', '__return_false');

However, the latest WordPress Popular Posts will use the rest_url to do post views count:

'ajax_url' => esc_url_raw( rest_url( 'wordpress-popular-posts/v1/popular-posts/' ) )

**Comment by cabrerahector** [comment]
Hi @portablesoft,

No, unfortunately that's not possible. WPP relies on the REST API to do various things, including -as you already noticed- keeping track of your site's views count.

Since WordPress itself will also be moving towards using the REST API everywhere (mainly because of Gutenberg) chances are WPP won't stop using it unless a suitable (and more efficient) alternative is introduced, something I honestly don't expect to see anytime soon.
