### ISSUE TITLE
WPP doesn't count frontpage views

### ISSUE THREAD

**Issue by jh-isw** [cabrerahector/wordpress-popular-posts#215]
Hello,
thanks for the useful plugin.
I have a question: is it possible to count views of the front page? WPP counts sub-pages and posts, but not the index page.

Thanks in advance

**Comment by cabrerahector** [comment]
Hi there,

Yes, it is possible. However, the homepage being excluded by the plugin is by design and mainly for two reasons:

1. The homepage is the single most visited page of 99.99% of the websites out there. Because of that, the homepage would be perpetually at the top of the popular posts list which wouldn't be really helpful to visitors (and why would visitors want to see the homepage on the list anyways?)
2. Tracking the views count of the homepage would mean -as obvious as this might sound- writing to the database every single time someone lands there. This can have an impact on the performance of the site because -as explained before- this is usually the most viewed page of any site, and many views = many database writes.

**Comment by jh-isw** [comment]
Thanks for your quick reply.
Mainly, I started using WPP because it's interesting to me, how often a post gets viewed.
Now I would like to see any page hit including the front page. 
I will have a look, if another plugin suits this need better, otherwise come back here and ask for how it's done to switch it on in your plugin.

Greetings, Jan

**Comment by cabrerahector** [comment]
Alright, if you have any further questions don't hesitate to ask.
