### ISSUE TITLE
Wrong post_id in wpml installation

### ISSUE THREAD

**Issue by giovanni-ctmobi** [cabrerahector/wordpress-popular-posts#227]
In case of wpml installation get write in db the wrong post_id ( the default language's post id )

Let's suppose that i have a default language in wpml as eng
1) Create a post in one language ( eng ) and create it's translation ( ita )
2)Visit both language version
3) From the db you can't see the visit from the ita version of the post and instead, you have one more visit from the eng version of that post. 

**Environment:**
 - WordPress version:4.9
 - PHP version: 7.2
 - Plugin version: 5.0

**Comment by cabrerahector** [comment]
Hi @giovanni-ctmobi,

> From the db you can't see the visit from the ita version of the post and instead, you have one more visit from the eng version of that post.

That's the expected behavior, actually. Both the english version and the italian version of your post share the same views count. See [WPP only in current language (with WPML)](https://github.com/cabrerahector/wordpress-popular-posts/issues/102#issuecomment-354177101) for more details.
