### ISSUE TITLE
WebP Issue

### ISSUE THREAD

**Issue by PhillipHuynh** [cabrerahector/wordpress-popular-posts#235]
**Describe the bug**

With the combination of EWWW, WP Rocket, and WPP, it seems like WPP is not serving the WebP versions correctly. Investigating the "wordpress-popular-posts" folder, I can see the WebP files are in there. However, on the front end side, it is trying to serve the WebP without the original image extension.

IE:

97544-featured-100x75.png.webp - Correct Filename
97544-featured-100x75.webp - Incorrect Filename <--- This one is being served on the frontend

**To Reproduce**
1. Go to 'https://www.provideocoalition.com/'
2. Scroll down to 'Popular' widget

**Expected behavior**

The correct image should be displaying.

**Screenshots**

**Environment:**
 - WordPress version: [5.2.4]
 - PHP version: [7.2.19]
 - Database version: [MySQL 5.7.23]
 - Plugin version: [5.0]
 - Active plugins: [EWWW, WP Rocket, WPP]

**Comment by cabrerahector** [comment]
Hi @PhillipHuynh,

WordPress Popular Posts generates & retrieves images using WordPress' core functions (eg. [wp_get_image_editor()](https://github.com/cabrerahector/wordpress-popular-posts/blob/5.0.0/src/Image.php#L657)) so I'm not sure if there's anything I can do to help here since these functions are out of the control of the plugin. Please get in touch with the team behind the EWWW plugin (which I assume it's responsible for generating the .webp images, I have never used it myself) and see what they have to say about the matter. Let me know if there's anything else I can do to help out.
