### ISSUE TITLE
Cannot Clear Dashboard Message

### ISSUE THREAD

**Issue by reneedobbs** [cabrerahector/wordpress-popular-posts#243]
Cannot clear this message on the dashboard:
WordPress Popular Posts: It seems your site is popular (great!) You may want to check these suggestions to make sure your website's performance stays up to par.

**To Reproduce**
1. Go to WordPress dashboard
2. See message
3. No way to clear it.

**Expected behavior**
Should have an "X" or something to clear the message.

**Screenshots**
![WP Popular Posts Message](https://user-images.githubusercontent.com/45937852/72627202-11df4800-391a-11ea-888d-0f873f626563.jpg)

**Environment:**
 - WordPress version: 5.3.2

**Comment by cabrerahector** [comment]
Hi @reneedobbs,

That's not a bug. It's the intended behavior.

Currently only site admins can dismiss the notice because it's performance related, an important aspect for the site's health: if you don't configure your website to make sure WPP doesn't it slow down in the (near) future there's a high probability that your site's performance will take a hit, hence the reason why the plugin doesn't allow authors/editors/subscribers to hide the notice.

With that being said, there's a workaround to hide the performance notice:

- Add `wpp_dismiss_performance_notice=1` to the URL in the address bar (eg. `https://www.your-website.com/wp-admin/?wpp_dismiss_performance_notice=1`) then hit Enter and the notice will be dismissed forever.
- Add `wpp_remind_performance_notice=1` to the URL in the address bar (eg. `https://www.your-website.com/wp-admin/?wpp_remind_performance_notice=1`) then hit Enter and the notice will be dismissed for the next 24 hours or so.

Again, I cannot stress enough the importance of following the [performance suggestions](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance) as noted by the alert bar. Please make sure to talk to your site's administrator about this notice to make sure your site continues to operate smoothly in the future when using the WPP plugin.

**Comment by cabrerahector** [comment]
As a sidenote, I might change this behavior in a future release allowing administrators and editors to hide the notice but for the time being the workaround described above is the way to go if your WordPress account doesn't have admin capabilities.
