### ISSUE TITLE
Gutenberg Block

### ISSUE THREAD

**Issue by bricedupuy** [cabrerahector/wordpress-popular-posts#249]
Any chance you could make a Gutenberg Block with the features you already have?
Allowing for easy customisation :
- layout (show/hide featured image, author, category, date, etc.)
- Category/Taxonomy picker
- CPT picker
- Date range
- etc.

**Comment by cabrerahector** [comment]
Hi @bricedupuy,

There are plans to do this sometime in the future. The reason why there isn't a WPP Gutenberg block as of yet (and I'm going to quote myself from a [comment](https://wordpress.org/support/topic/shortcodes-generator-for-wpp/#post-12408022) I left on the support forums here) is this:

> (...) the WordPress team is planning to [make everything -including widgets- a Gutenberg block](https://github.com/WordPress/gutenberg/issues/13113) (...) **I’d rather wait a bit and see where things go.**

Since I don't know _how_ exactly the Gutenberg team is planning to do this it'd be a waste of time for me to go and implement a WPP block to then later realize -for example- that the widget can be used as a Gutenberg block as it is now without me having to do any code changes (unlikely IMO but who knows?)

So, as stated in the comment, _I'd rather wait and see_.

**Comment by cabrerahector** [comment]
It's been a while but figured I'd post an update here since you (and everyone else reading this) might be interested.

Since [Full-Site Editing](https://developer.wordpress.org/block-editor/handbook/full-site-editing/) is [coming soon](https://make.wordpress.org/core/2021/06/04/whats-next-in-gutenberg-june-2021/) I decided it was time to give Gutenberg another try. It turns out that there's a [Legacy Widget block](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/widgets/legacy-widget-block.md) (recently introduced) that provides some compatibility with existing non-block based, third-party widgets. Unfortunately though at the time of writing it doesn't work very well with WordPress Popular Posts.

Due to the above and since I was curious anyways I started coding a custom WPP block. You can see a small preview here: https://www.buymeacoffee.com/cabrerahector/playing-around-gutenberg

There's still a lot of work ahead before I can share it publicly (the animated preview in that post is already "old", I added more changes & features within the past few days). So far progress has been promising, it's been more fun than I expected.

If everything goes well I might publish the new block and label it as _experimental_ / _expect-minor-issues_ for everyone to try out. Hopefully before FSE launches, that's if work / life allows it haha.

**Comment by cabrerahector** [comment]
The WPP block is now available to everyone without needing to enable the experimental features option (see 218abca) so I'm closing this now.
