### ISSUE TITLE
{date} is not translated into locale language

### ISSUE THREAD

**Issue by zebrastribe** [cabrerahector/wordpress-popular-posts#278]
![Skærmbillede 2020-10-28 kl  14 28 40](https://user-images.githubusercontent.com/6557899/97442214-e1591f80-1929-11eb-9047-e10c5ad7d24e.png)
I use the {date} tag but it does not translate into swedish (also need in danish, norwegian).

How can I translate it?

**Comment by cabrerahector** [comment]
Hi @zebrastribe,

If you're using the plugin version from wordpress.org then in order to translate dates you'll need to create a translation file for Danish & Norwegian as detailed [here](https://wordpress.org/support/topic/wordpress-popular-posts-translations/#post-12459753).

If you're using the GitHub version of the plugin then make sure WordPress has the language pack files for danish and norwegian installed in your **/wp-content/languages** folder for WPP to be able to translate dates. One easy way to get WordPress to automatically get these language packs for you:

1. Go to **Settings > General**.
2. Set **Site Language** to Danish and save changes.
3. Go to **Dashboard > Updates** and click on **Check Again**. This will force WordPress to check for updates and detect that you need a new language pack. You should see that there are new translations available at the bottom of the page. Follow the instructions to install them on your site.
4. When that's done, go back to step 2, set the site language to Norwegian and follow the same process as before.
5. Finally, change your site's language back to whatever it was.
6. Profit!

**Comment by zebrastribe** [comment]
I use the the version from the Wordpress repo. The language is set to swedish in wordpress and the timezone is stockholm. Also there is a swedish translation inside the Moment/locales/ folder. And there is also a swedish language files inside wp-content/languages/ 

The admin part of WPP is partly translated into swedish...

![Skærmbillede 2020-10-29 kl  09 37 04](https://user-images.githubusercontent.com/6557899/97544735-50865080-19ca-11eb-8ff8-9028e659d0d7.png)

But on the site the texts is in english...

(PS. Sure you can use the design the font is Bebas neue and Roboto:)
https://fonts.google.com/specimen/Bebas+Neue
https://fonts.google.com/specimen/Roboto+Condensed

**Comment by cabrerahector** [comment]
Alright, I'll see if I can reproduce this as soon as I get some spare time. Right now I'm swamped with work T_T

I'll leave a comment after testing.

**Comment by cabrerahector** [comment]
Hey @zebrastribe,

So the Swedish locale file included in [wp-content/plugins/wordpress-popular-posts/src/Moment/Locales](https://github.com/cabrerahector/wordpress-popular-posts/tree/5.2.4/src/Moment/Locales) seems to be misnamed. The file is currently named as _se_SV.php_, while WordPress uses _sv_SE_ when setting the site language to Swedish. Renaming said file as _sv_SE.php_ fixes the issue for me so give it a shot and report back.

Please keep in mind that this is just a **temporary** workaround: the GitHub version of the plugin no longer uses the referenced Moment library to translate dates. Once I release this version on wordpress.org this workaround will no longer work so you should follow the instructions I posted earlier to download the official language packs for Danish (Swedish?) and Norwegian so future WPP releases can translate dates properly.

**Comment by zebrastribe** [comment]
Great stuff. Looking forward to the update. Thank you for all your help
