### ISSUE TITLE
Hide articles that do not have translations

### ISSUE THREAD

**Issue by LevelUpGit** [cabrerahector/wordpress-popular-posts#286]
Hi, 
we are using polylang with your plugin, and it works as excepted, except your plugin is pulling articles that do not have translation 
in the list along side with those that have translation.

What would be best is that for those articles that do not have translation to not be pulled.

Thank you.

**Comment by cabrerahector** [comment]
Hi there,

Unfortunately that's not possible. WordPress Popular Posts expects for all posts to have a translation available for the currently active language, otherwise -as you already noticed- the original article will be displayed instead.

This is explicitly mentioned on the [Description](https://wordpress.org/plugins/wordpress-popular-posts/) page of the plugin:

> **Polylang & WPML 3.2+ support** – Show the translated version of your popular posts!

**Comment by LevelUpGit** [comment]
Thank you for your fast response.
