### ISSUE TITLE
How to display total approved comments count?

### ISSUE THREAD

**Issue by dr1361teh** [cabrerahector/wordpress-popular-posts#299]
Hello,
I use the following code to show the popular post ordered by number of comments :

`<?php
if ( function_exists('wpp_get_mostpopular') ) {
    wpp_get_mostpopular(array(
        'range' => 'weekly',
	'stats_comments' => 1,
        'order_by' => 'comments',
        'limit' => 10
    ));
}
?>`

What should I do to show the **total approved comments** count and ignore the date range for weekly most commented posts ?
Thanks

**Comment by cabrerahector** [comment]
Hi @dr1361teh,

The code you're using will display the total number of comments received _within the last 7 days._ The plugin doesn't offer a way to display total comments count.

If you want to display the total comments count then you'll need to create a custom Content Tag, like `{total_comments}` for example, and then modify the HTML output of the function so it displays this new tag instead of the default one. Check the following links for more details:

- [Display Tags and Author Image](https://wordpress.org/support/topic/display-tags-and-author-image/#post-14706223) (with this one you'll learn how to create custom content tags)
- [How can I use my own HTML markup with WordPress Popular Posts?](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-can-i-use-my-own-html-markup-with-your-plugin) (and this explains how to customize the HTML output)

If you have any questions don't hesitate to ask.
