### ISSUE TITLE
Loading bunch of scripts even when not using the new block

### ISSUE THREAD

**Issue by roelmagdaleno** [cabrerahector/wordpress-popular-posts#300]
**Describe the bug**

The new WPP version (`v5.4.0`) is enqueuing a bunch of scripts for the new Gutenberg Block even when I'm not using the Block (see screenshot). Unfortunately this affects performance and PageSpeed Insights scores.

The culprit is inside of the `Block/Widget/Widget.php` file, method `register()`. Line 132.

Also, I have installed Classic Widgets plugin and is still enqueueing the scripts. And, if I disable WPP plugin the scripts listed in the screenshot are gone.

**Expected behavior**

Before enqueuing the Gutenberg Block needs a validation to detect whether the current post contains the block. For example,

```php
if ( ! has_block( 'wordpress-popular-posts/widget' ) ) {
   return;
}

wp_enqueue_script(
    'block-wpp-widget-js',
    plugin_dir_url(dirname(dirname(dirname(__FILE__)))) . 'assets/js/blocks/block-wpp-widget.js',
    ['wp-blocks', 'wp-i18n', 'wp-element', 'wp-block-editor', 'wp-server-side-render'],
    filemtime(plugin_dir_path(dirname(dirname(dirname(__FILE__)))) . 'assets/js/blocks/block-wpp-widget.js')
);
```

Reference:
https://developer.wordpress.org/reference/functions/has_block/

**Screenshots**

![image](https://user-images.githubusercontent.com/3928004/130388821-eb752ce0-9f1a-4bc4-a87d-7d59d139f5ab.png)

**Environment:**
 - WordPress version: 5.8
 - PHP version: 7.4

**Comment by cabrerahector** [comment]
Hola Roel,

The issue has been reported on the support forum already but thanks for the heads-up anyways :)

The issue I have with using the `has_block()` function is that it only works on posts. If you add the block to a sidebar on your homepage for example then adding this check will prevent users from seeing the block there which isn't great either.

Anyways, this issue has been fixed with commit 38b6d05. There's really no need to use this check, it was a mistake on my part what caused WordPress to load all of these files on the front-end (but your report indirectly helped me notice it so once again thanks). Please update to version 5.4.1 as soon as you get the chance.
