### ISSUE TITLE
Fatal error: Cannot declare ....

### ISSUE THREAD

**Issue by mcanady** [cabrerahector/wordpress-popular-posts#301]
I'm getting this error when installing the plugin on a site in which I had an earlier version of this plugin installed. WordPress 5.8 running MH Magazine theme. Any ideas on how to fix?

Fatal error: Cannot declare class ComposerAutoloaderInit2a403b03a84e333364c96d224aa62f5c, because the name is already in use in /home/customer/www/sdbn.org/public_html/wp-content/plugins/wordpress-popular-posts-master/vendor/composer/autoload_real.php on line 5

**Comment by cabrerahector** [comment]
Hi @mcanady,

Do you have two versions of the WPP plugin installed on your site? Because that'd explain why you're getting this error.

The other possible explanation is that you have another plugin that also happens to have a PHP class named _ComposerAutoloaderInit2a403b03a84e333364c96d224aa62f5c_ (or even a PHP class in your theme) but the odds of that happening are very, _very_ low.

**Comment by mcanady** [comment]
Thanks! Sorry I got confused, I think I was trying to re-install it. I have another question about your WPP feed plugin, will post on that site.
