### ISSUE TITLE
How to add 2 custom field name for thumbnail images

### ISSUE THREAD

**Issue by cpaj** [cabrerahector/wordpress-popular-posts#323]
Hello,

It's a great plugin but I am stuck at a point where I want to add 2 custom field names for thumbnail in the "Custom Field Name" section in the plugin tool section.

Currently, I can only add one custom field name for thumbnail images but I have 2 custom field names that I need to add in the "Custom Field Name" section to display the thumbnail images.

Please help me and let me know if it is possible, it will be a great help for me.

Thanks,
Abhishek Joshi.

@cabrerahector

**Comment by cabrerahector** [comment]
Hi @cpaj,

To help you out I need some more context. Why do you need two custom fields exactly?

**Comment by cpaj** [comment]
> Hi @cpaj,
> 
> To help you out I need some more context. Why do you need two custom fields exactly?

Thanks a lot for quick reply.
I have one taxanomy under which there are two different taxonomy type in which there are 2 different custom field name for thumbnail images. For eg
Parent name resources: child name Blog
Parent name resources: child name case study

Now blog and case study both have custom field image name but both custom field name are different.
And that I need to add in custom field text box in the plugin.

I hope I was able to explain it.
Please let me know if you have any questions.

**Comment by cabrerahector** [comment]
Adding a custom text field to the plugin's settings is not possible at the moment. You may want to consider a different approach: you can instead [change the HTML output](https://github.com/cabrerahector/wordpress-popular-posts/wiki/5.-FAQ#how-can-i-use-my-own-html-markup-with-your-plugin) of your popular posts list so it renders your custom field images they way you want it without needing to add one or more fields to the plugin's settings page.

Here are a couple of real-life from the forum that may help:

- [ACF field integration?](https://wordpress.org/support/topic/acf-field-integration/)
- [Display tags and author image](https://wordpress.org/support/topic/display-tags-and-author-image/).

If you have any questions don't hesitate to ask, alright?

**Comment by cpaj** [comment]
Yes I can change the WordPress setting for ACF plugin and make the changes but at this moment website is so big that I cannot make changes to it as of now. But can you please consider this as an suggestion and add the functionality in your next update. It will be very helpful.

If you could help me to make any changes directly in plugins files and help me to achieve my requirement?

**Comment by cabrerahector** [comment]
> Yes I can change the WordPress setting for ACF plugin and make the changes but at this moment website is so big that I cannot make changes to it as of now.

You could try making these changes on your local development machine and/or a [staging site](https://umbraco.com/knowledge-base/staging-environment/). That way you can test changes without affecting the live website if that's what worries you.

> can you please consider this as an suggestion and add the functionality in your next update. It will be very helpful.

Sorry, I have no plans to add this.

> If you could help me to make any changes directly in plugins files and help me to achieve my requirement?

Changing plugin's files directly is not a good idea, Abhishek: every time you update the plugin WordPress will undo all of the changes made to it. You'd need to redo the mod every single time a new version is out. That's why many plugins out there (including WPP) include [filter / action hooks](https://developer.wordpress.org/plugins/hooks/) so other developers -like yourself- can change their behavior from the outside without having to "hack" the plugin.

My advice is to follow the suggestion from my previous comment, it's less problematic and it's more future proof.
