### ISSUE TITLE
Inflating view counts to game post popularity

### ISSUE THREAD

**Issue by richvida** [cabrerahector/wordpress-popular-posts#44]
Is there anything preventing a person from inflating view counts?

It seems to be that any post could be gamed as a popular post by anyone determined to refresh the page enough times.

**Comment by cabrerahector** [comment]
It's been quite sometime since I last checked this issue!

Anyways, just added a new hook: *wpp_pre_update_views*. Should allow to perform an action right before updating the views count. Your custom action __must__ return a boolean:

* _true_, if you want WPP to continue to update the views count after your custom action is executed;
* _false_, if you want to prevent WPP from updating the views count after your custom action is executed.

Alternatively, you could also remove WPP's AJAX hooks and write your own functions - as @mbootsman suggested. The hooks are _wp_ajax_update_views_ajax_ and _wp_ajax_nopriv_update_views_ajax_.
