### ISSUE TITLE
Use WordPress thumbnails instead of generating own cache folder

### ISSUE THREAD

**Issue by ste93cry** [cabrerahector/wordpress-popular-posts#60]
After enabling the widget option to show the thumbnail image, I can select the dimension of the thumb. As a user, I would expect that the image is the one generated by WordPress core, not a copy stored under the `wp-content\uploads\wordpress-popular-posts` directory. I would suggest to use the standard WordPress functions to generate the thumbnail, like many other plugins do. As far as I know, WordPress still accepts custom dimensions for the images, so backward supports should be possible.

**Comment by cabrerahector** [comment]
It's been implemented like this so the plugin can remove the thumbnails created by it during uninstall. I do, however, understand what you mean since another user at the WordPress forums also mentioned it.

The selectable thumbnail dimension feature is a new ability introduced with the last official version of the plugin, and of course there's room for improvement. I'll look into it once I get some spare time. Picking a custom size (the "manual" option) will still store thumbnails on the wordpress-popular-posts folder though.

**Comment by ste93cry** [comment]
Imho it's really important to standardize the way plugins interact with the "core" features of WordPress, like the thumbnails management.

> Picking a custom size (the "manual" option) will still store thumbnails on the wordpress-popular-posts folder though.

I now understood why you saved the images in your custom folder, btw I don't agree with it. I don't see why a plugin should remove the images it created when uninstalled. I know that data depends on your plugin, but if you use WordPress functions to generate a thumbnail with custom dimensions this means that even if a user changes plugin he still can use the generated thumbnails.

**Comment by cabrerahector** [comment]
It's OK to disagree. I'm usually open to discussions as these often lead to making things better, so thanks for taking the time to share your thoughts on the matter.

I'll think about it. As I said before, there's always room for improvements so suggestions are welcome.

**Comment by ste93cry** [comment]
> As I said before, there's always room for improvements so suggestions are welcome.

Thank you for creating this fantastic plugin, keep up the good work!

**Comment by zulkamal** [comment]
A project I'm working on also requires the use of core's `get_the_post_thumbnail` as the images are hosted on S3 (via Amazon S3 Plugin). What I did was choose set the custom field name to "amazonS3_info" and updated `_get_thumb()` to check for that:

    if ($this->user_settings['tools']['thumbnail']['source'] == "custom_field") {
      if ($this->user_settings['tools']['thumbnail']['field'] == "amazonS3_info") {
	    $thumb .= get_the_post_thumbnail($p->id, array($tbWidth, $tbHeight));
      }
      else {
        ... original code ...
      }

I'm calling the plugin via shortcode in a template by the way.

That said, perhaps a way to bake this is the plugin would be to add a new option to the plugin's "Pick image from: " setting for using core's `get_the_post_thumbnail()`. Since the `$size` argument allows string or array, there should be options for each widget/shortcode instance to use either a string or use the set width/height like my code above.

Hope this helps and thanks for the plugin!

**Comment by cabrerahector** [comment]
Hey guys,

As discussed, WPP will now use the stock thumbnails whenever possible assuming the following two conditions are met:

1. Thumbnail source is set to *Featured Image*, and
2. The widget is set to use one of the stock thumbnail sizes available.

The first condition is pretty much self-explanatory. The last one does require a bit of background:

As you probably already know, whenever you upload an image either via the *Featured Image* functionality or via the *Media Library*, WordPress creates a thumbnail of each size as specified via theme's functions.php (see [Enabling support for Post Thumbnails](http://codex.wordpress.org/Post_Thumbnails#Enabling_Support_for_Post_Thumbnails) and [add_image_size()](http://codex.wordpress.org/Function_Reference/add_image_size) for more).

When using the [get_the_post_thumbnail()](http://codex.wordpress.org/Function_Reference/get_the_post_thumbnail) function, you either should pass the thumbnail size as a string (eg. 'thumbnail') or as an array with the desired width and height (as @zulkamal suggested above). However, the latter has a catch that isn't documented on the codex: if there's no match -that is, there's no thumbnail with the exact same width and height- WordPress will give you the closest in size it finds.

What's the problem with the above, you ask?

1. the resulting thumbnail will be a *scaled down* version of a bigger image, which may or may not fit the desired width & height, and
2. the browser will be downloading a bigger image than what you actually need, increasing the loading time of the page.

That is why WPP has been creating custom images all along instead of relying on WordPress' [get_the_post_thumbnail()](http://codex.wordpress.org/Function_Reference/get_the_post_thumbnail) function - to make the user's life easier and save him from having to create custom thumbnail sizes via theme's functions.php. The tradeoff is that WPP will need to store its image on a custom folder to keep track of them.

**Comment by ste93cry** [comment]
Thank you for not forgetting us :smile: nice plugin, nice support from the author :+1: just one note: I discourage the use of the syntax below (seen [here](https://github.com/cabrerahector/wordpress-popular-posts/commit/f2e721f737f30ba0be2db232c18c23b9ef352b92#diff-3e4b9008957049dbbd087d0a3028b3bbR2067)), it's less clear than using the curly brackets imo.

**Comment by andresg747** [comment]
Thank you @zulkamal !!
