### ISSUE TITLE
Widget text fields doesn't specify proper input type

### ISSUE THREAD

**Issue by ste93cry** [cabrerahector/wordpress-popular-posts#61]
Many widget input fields don't have the `text` HTML property specified, leading to inconsistent layout theming. You can see the image below for a comparison of a field with the correct HTML markup vs all other input fields.

![wp-popular-posts-input](https://cloud.githubusercontent.com/assets/1770485/5741016/bf35f418-9c08-11e4-8519-a5910f5aee86.png)

**Comment by cabrerahector** [comment]
It's probably been like that since the early days of the plugin and nobody ever mentioned it until now. Thanks for pointing it out, otherwise I'd have never noticed it.

I was trying to avoid working on the plugin now since I'm actually busy with work projects at the time, but since it's an easy fix I'll look into it right away.

**Comment by ste93cry** [comment]
As this is not something breaking the plugin, you can even wait until the next plugin version to update it, maybe with the other changes discussed in #60 and #59

**Comment by cabrerahector** [comment]
I know, but the problem is that I *know*. Can't leave it like that now hehe. I won't push an official update just yet, just the fixes to this repo since I know that a couple of people out there are using the Github version since it's more up-to-date than the one published at the WordPress repo.
