### ISSUE TITLE
Unique views across multiple languages

### ISSUE THREAD

**Issue by egnsh93** [cabrerahector/wordpress-popular-posts#64]
What about being able to have different popular posts across multiple languages (with different view dates, number of views, etc...). At the moment the plugin only supports a single "profile" and gets the appropriate translated metadata from WPML.

I am trying to think of a solution that would avoid changing the structure of the DB too much. What about on the plugin's first activation (or maybe a config setting), figuring out what languages the site supports, and dynamically create a table for each of them. When tracking views, just check for the active language. So basically the way it is currently setup in the DB, but then repeat for other languages?

**Comment by cabrerahector** [comment]
Hi Shane!

Someone at the WordPress forums also brought this up not so long ago. Since I already shared my thoughts on the matter over there, here's the [link to the topic](https://wordpress.org/support/topic/wpml-second-language-post-mirror-the-primary-language "WPML - Second Language Post Mirror the Primary Language").

About the idea of setting up multiple language tables - to be honest, I don't feel too excited about it. As you said yourself, that would require modifying the DB structure and that's something I'd like to avoid if I can help it. This doesn't necessarily mean I'm rejecting the idea completely, though.

**Comment by egnsh93** [comment]
I don't really see an elegant solution that doesn't involve modifying the structure of the database. With that in mind, if the DB were to be setup slightly different, a composite key could be used to link a post ID with the locale (or WPML language), and breaking up the table accordingly.
