### ISSUE TITLE
XMLHttpRequest Security Vulnerability

### ISSUE THREAD

**Issue by richvida** [cabrerahector/wordpress-popular-posts#67]
Hi Hector,

Can anything be done with all these WordPress references?

Previously my issue https://github.com/cabrerahector/wordpress-popular-posts/issues/43 asked about the HTML comments used for debugging — which I've been able to remove using a regex.

However, this time it has to do with the (new?) `XMLHttpRequest object` which gives away the install location of WordPress. 
   
    url = 'http://localhost/wordpress/wp-admin/admin-ajax.php'

It's my opinion that any website using WordPress should do its best to hide that fact as a simple security precaution.

I love this plugin and would prefer to not be manually altering its code.

Thanks,
Rich

**Comment by cabrerahector** [comment]
Hi Rich,

Actually, WPP has been using the admin-ajax.php URL for a very long time
now. The only change made recently was the switch from jQuery's AJAX
handler to XHR for performance reasons.

Also, since WPP uses Ajax to communicate with the database there's no way
to "hide" the URL. That's just how WordPress works.

**Comment by richvida** [comment]
Hector,

Thanks for the really quick response!

Do you think there's anything I can do to mask that URL?
