### ISSUE TITLE
Prepare queries to protect against SQL injection attacks

### ISSUE THREAD

**Issue by getdave** [cabrerahector/wordpress-popular-posts#83]
Skimming the source I noticed a SQL query being executed without `prepare()` first. It may be that the functions used above in `_query_posts()` help to validate data before usage, if so this may be irrelevant. However would it be worth looking at changing

https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L1680

to use prepared statements a la the [WordPress codex](https://codex.wordpress.org/Class_Reference/wpdb#Protect_Queries_Against_SQL_Injection_Attacks) 

``` php

// Build query
$query = "SELECT %s FROM %s %s %s %s %s";

$this->__debug( $query );

$sql = $wpdb->prepare( $query, array( $fields, $from, $where, $groupby, $orderby, $limit ) ); 

$result = $wpdb->get_results( $sql );
```

The above doesn't actually work (I suspect due to the way the query strings are built above) but it could be worth looking at debugging this in order to improve the security of the Plugin.

Many thanks again for excellent work developing this Plugin. It's worked very well so far.

**Comment by cabrerahector** [comment]
Hi Dave!

All of the parameters are validated either [here](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L508-L604) (widget form update) or [here](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/wordpress-popular-posts.php#L2798-L2843) (people using the [[wpp] shortcode](https://github.com/cabrerahector/wordpress-popular-posts/wiki/1.-Using-WPP-on-posts-&-pages) and/or [wpp_get_mostpopular() template tag](https://github.com/cabrerahector/wordpress-popular-posts/wiki/2.-Template-tags#wpp_get_mostpopular)). IMHO the plugin is quite secure as it is now.

Implementing prepared statements might not be completely straight forward because - as you already know - the query is built on the fly based on user's selections. Still, adding an extra layer of security is never a bad idea so I'll consider your suggestion for a future release :)

Thank you for contributing!

**Comment by getdave** [comment]
Hey @cabrerahector no worries. I suspected you'd probably covered this off. Thanks for considering my comments.

Thanks
