### ISSUE TITLE
PHP warning generated by update_views_ajax

### ISSUE THREAD

**Issue by twarkie** [cabrerahector/wordpress-popular-posts#87]
I just noticed that the error log file on one of our productions server is filled with these errors: 

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'update_views_ajax' not found or invalid function name in /[...]/wp-includes/plugin.php on line 496

Call Stack
Id	Time	Memory	Function	Location
1	0.0003	265496	{main}( )	../admin-ajax.php:0
2	0.4960	39916560	do_action( )	../admin-ajax.php:96
3	0.4960	39918304	call_user_func_array ( )	../plugin.php:496

The code seems to work anyway in that the views are collected, but is there anything that can be done about these warnings?

**Comment by cabrerahector** [comment]
Hi there!

That's sounds more like a WordPress bug than a problem caused by WPP.

WPP's *update_views_ajax* function which -as you already know- is used by WPP to update the views count of a post or a page. This is done by printing a small JavaScript code in the header of your site. However, for some reason, WordPress was unable to find the *update_views_ajax* function. Why? I honestly don't know.

The only way I can think of right now that could trigger this warning is if you're using a caching plugin and WPP was disabled at the time: the cached JavaScript code would ask WordPress to call the *update_views_ajax* function but since WPP isn't enabled WordPress would fail to find it, triggering that error message.

**Comment by twarkie** [comment]
Thanks for the reply!

We are in fact using W3-total-cache on the production server, but admin-ajax.php is bypassed. Our dev environment does not have any caching plugin but experiences the same problem.

Weird thing is that the views are updated even with the warning. I've been trying to debug myself but can't find any problem :-/

**Comment by cabrerahector** [comment]
If it still happens even without a caching plugin, then unfortunately I'm as lost as you are.

To be sure, I checked the logs of a couple of WordPress sites I run where WPP is installed and couldn't find any errors / warnings related to it (not even the one you posted above).

Normally I'd say "try disabling all of your plugins -except for WPP- and see if the issue persists", but in your case I'm not too sure that'll fix it.
