### ISSUE TITLE
Do not run upgrades for every user that loads a page.

### ISSUE THREAD

**Issue by Alexia** [cabrerahector/wordpress-popular-posts#99]
This query runs when ANY and ALL users load a page when upgrading from 2.3.7 to any newer version.  This is horrible and causes immediate database crashes.

```
					$sql = "
					INSERT INTO {$prefix}summary (postid, pageviews, view_date, last_viewed)
					SELECT id, pageviews, day_no_time, day
					FROM {$prefix}datacache
					GROUP BY day_no_time, id
					ORDER BY day_no_time DESC";

					$result = $wpdb->query( $sql );
```

**Comment by cabrerahector** [comment]
Hi Alexia!

Actually, version 2.3.7 also runs a similar DB query on every page load ([here](https://plugins.trac.wordpress.org/browser/wordpress-popular-posts/tags/2.3.7/wordpress-popular-posts.php#L795) when the "Ajaxify widget" option is enabled, and [here](https://plugins.trac.wordpress.org/browser/wordpress-popular-posts/tags/2.3.7/wordpress-popular-posts.php#L555) when it's not).

The only difference is between v2.3.7 and newer releases -when it comes to page views tracking- is that the former only logs visits from non-logged in users (this is the default behavior, and can be set to log every visit as well) while from [3.1.0](https://github.com/cabrerahector/wordpress-popular-posts/blob/master/changelog.md#310) and on is the other way around: WPP logs every page view from everyone (new installs only, can also be configured). Other than that, WPP basically does pretty much the same thing to track the page views since around v1.3 I think.

If your database is crashing it either means that it became too large or that your site is receiving a lot of visitors, or both. You should check the [Performance section](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance) for suggestions.

**Comment by Alexia** [comment]
That is the query that upgrades from the old style tables to the newer style tables.  It does this by invoking WordpressPopularPosts::__upgrade() for every person that loads a page on the site.  As you can imagine attempting to copy the contents of one table to another table then convert that table from HEAP to MYISAM hundreds times would cause a crash.  This is a coding issue.

**Comment by cabrerahector** [comment]
Indeed, the __upgrade() method copies the data from the old _datacache_ table to the _summary_ table which is a one-time thing. Once it's done, WPP deletes _datacache_ from the database and so this process (data migration) won't be executed again on future plugin updates.

As a side note, WPP tables are set to use _InnoDB_. WPP also tries to convert them into InnoDB on plugin upgrade. Seeing that yours were converted to MyISAM after upgrading means that your current hosting has disabled the InnoDB engine. Normally this wouldn't be an issue, but since we're talking about a script that constantly writes to the database you should ask them to enable the InnoDB engine for you. The MyISAM engine isn't recommended for high-write operations (while InnoDB is optimized for that). If this is not possible, then you should either enable [Data Sampling](https://github.com/cabrerahector/wordpress-popular-posts/wiki/7.-Performance#data-sampling) to lower the impact to the database or move your site to another hosting with InnoDB enabled.

**Comment by Alexia** [comment]
"which is a one-time thing."

Right, it is supposed to be a one time operation.  However, that operation gets invoked for every page load until it completes.  So if it is sitting there for a while still processing more and more invocations of the same database queries get pushed into the database.

Basically:
Visitor #1: WPP sees the database needs upgraded, begins the upgrade process.
Visitor #2: Upgrade process invoked by Visitor #1 is not done yet, WPP sees the database needs upgraded, WPP begins the upgrade process...

This repeats until database connections are maxed out and the server load increases until it crashes.

We're using Percona's MySQL fork and we manage our hosting.  We do have InnoDB enabled.

**Comment by cabrerahector** [comment]
Ah, I see what you mean now. Should be fairly simple to fix.

> We're using Percona's MySQL fork and we manage our hosting. We do have InnoDB enabled.

I found the reason why WPP was unable to convert your tables to InnoDB: WPP only makes the conversion if the current engine is MyISAM (which isn't right, WPP should attempt to make the conversion _if_ the engine isn't InnoDB). In your case, it was HEAP.

For the time being, please run these queries to change the engine into InnoDB:

```
ALTER TABLE wp_popularpostsdata ENGINE=INNODB;
ALTER TABLE wp_popularpostssummary ENGINE=INNODB;
```

Make sure to change the `wp_` prefix if your site is using a different one.

**Comment by cabrerahector** [comment]
Update: commits 115b412 and bd1371c should fix the issue.
